### ISSUE TITLE
Can not create highlight starting at position 0 of a text.

### ISSUE THREAD

**Issue by steffres** [acdh-oeaw/apis-core#291]
When marking right from the start of a text, at position 0, then it fails with the error:

```
[24/Sep/2021 10:35:57] "GET /apis/vocabularies/autocomplete/sundayrepresentations/normal/?q=son HTTP/1.1" 200 85
Internal Server Error: /apis/relations/ajax/save/passage/SundayHighlighterForm/10/
Traceback (most recent call last):
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/steff-vm/coladay/dev_instance/root_coladay_dev/apis-webpage-base/apis_core/apis_relations/views.py", line 219, in save_ajax_form
    types=entity_types_highlighter)[0].strip(),
  File "/home/steff-vm/coladay/dev_instance/root_coladay_dev/apis-webpage-base/apis_highlighter/highlighter.py", line 48, in highlight_text_new
    lst_annot[-1].append(an)
IndexError: list index out of range
```

**Comment by steffres** [comment]
Fixed in apis_highlighter repo, commit 62c9cc7325409c39aa133eb2e42842c579dbe62c
